/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Untitled: THREE.Mesh
    Untitled001: THREE.Mesh
    Untitled002: THREE.Mesh
    Untitled003: THREE.Mesh
    Untitled004: THREE.Mesh
    Untitled005: THREE.Mesh
    Untitled006: THREE.Mesh
    Untitled007: THREE.Mesh
  }
  materials: {
    palette: THREE.MeshStandardMaterial
    ['palette.001']: THREE.MeshStandardMaterial
    ['palette.002']: THREE.MeshStandardMaterial
    ['palette.003']: THREE.MeshStandardMaterial
    ['palette.004']: THREE.MeshStandardMaterial
    ['palette.005']: THREE.MeshStandardMaterial
    ['palette.006']: THREE.MeshStandardMaterial
    ['palette.007']: THREE.MeshStandardMaterial
  }
}

export function CharMKW(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CharMKW.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Untitled.geometry} material={materials.palette} position={[0.05, 0.7, 0.04]} rotation={[1.5, 0, 0]} />
      <mesh geometry={nodes.Untitled001.geometry} material={materials['palette.001']} position={[-0.3, 0.7, 0]} rotation={[0.14, 0, 0]} />
      <mesh geometry={nodes.Untitled002.geometry} material={materials['palette.002']} position={[-0.02, 0.52, 0.01]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Untitled003.geometry} material={materials['palette.003']} position={[-0.15, 0.3, 0]} rotation={[1.63, -0.09, 0.01]} />
      <mesh geometry={nodes.Untitled004.geometry} material={materials['palette.004']} position={[0.15, 0.3, 0]} rotation={[1.51, 0.02, 0]} />
      <mesh geometry={nodes.Untitled005.geometry} material={materials['palette.005']} position={[0.3, 0.7, 0]} rotation={[0.07, 0, 0]} />
      <mesh geometry={nodes.Untitled006.geometry} material={materials['palette.006']} position={[0.86, 0, -0.47]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Untitled007.geometry} material={materials['palette.007']} position={[0.93, -0.02, -0.37]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/CharMKW.glb')
