/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Untitled: THREE.Mesh
    Untitled001: THREE.Mesh
    Untitled002: THREE.Mesh
    Untitled003: THREE.Mesh
    Untitled004: THREE.Mesh
    Untitled005: THREE.Mesh
    Untitled006: THREE.Mesh
    Untitled007: THREE.Mesh
    Untitled008: THREE.Mesh
  }
  materials: {
    palette: THREE.MeshStandardMaterial
    ['palette.001']: THREE.MeshStandardMaterial
    ['palette.002']: THREE.MeshStandardMaterial
    ['palette.003']: THREE.MeshStandardMaterial
    ['palette.004']: THREE.MeshStandardMaterial
    ['palette.005']: THREE.MeshStandardMaterial
    ['palette.008']: THREE.MeshStandardMaterial
    ['palette.023']: THREE.MeshStandardMaterial
    ['palette.024']: THREE.MeshStandardMaterial
  }
}

export function CharMKG(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CharMKG.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Untitled.geometry} material={materials.palette} position={[0.07, 0.7, 0.04]} rotation={[1.5, -0.05, 0]} />
      <mesh geometry={nodes.Untitled001.geometry} material={materials['palette.001']} position={[-0.29, 0.63, -0.01]} rotation={[-1.44, -0.46, -0.03]} />
      <mesh geometry={nodes.Untitled002.geometry} material={materials['palette.002']} position={[0, 0.53, 0.01]} rotation={[Math.PI / 2, -0.05, 0]} />
      <mesh geometry={nodes.Untitled003.geometry} material={materials['palette.003']} position={[-0.15, 0.31, 0]} rotation={[1.63, -0.23, 0.01]} />
      <mesh geometry={nodes.Untitled004.geometry} material={materials['palette.004']} position={[0.15, 0.3, 0]} rotation={[1.44, 0.02, 0]} />
      <mesh geometry={nodes.Untitled005.geometry} material={materials['palette.005']} position={[0.3, 0.7, 0]} rotation={[1.53, 0.42, 0.02]} />
      <mesh geometry={nodes.Untitled006.geometry} material={materials['palette.008']} position={[-0.49, 0.97, 0.1]} rotation={[0.12, 0.14, 0.29]} scale={0.65} />
      <mesh geometry={nodes.Untitled007.geometry} material={materials['palette.023']} position={[0, 0, 1.1]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Untitled008.geometry} material={materials['palette.024']} position={[-1.65, 0.4, -1.42]} rotation={[1.64, 0, 0]} scale={0.76} />
    </group>
  )
}

useGLTF.preload('/CharMKG.glb')
